"""initial schema

Revision ID: ef0c6c6335ef
Revises: 
Create Date: 2026-05-14 00:08:30.168723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef0c6c6335ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".artists_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='artists_pkey'),
    schema='public'
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".customers_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    sa.UniqueConstraint('email', name='customers_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='public',
    postgresql_ignore_search_path=False
    )
    op.create_table('venues',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".venues_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), server_default=sa.text("'US'::character varying"), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='venues_pkey'),
    schema='public'
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".events_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['public.venues.id'], name='events_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_pkey'),
    schema='public'
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".orders_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['public.customers.id'], name='orders_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
    schema='public',
    postgresql_ignore_search_path=False
    )
    op.create_table('event_artists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".event_artists_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['public.artists.id'], name='event_artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['event_id'], ['public.events.id'], name='event_artists_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_artists_pkey'),
    schema='public'
    )
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".sections_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['public.events.id'], name='sections_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sections_pkey'),
    schema='public'
    )
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"public".order_items_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['public.orders.id'], name='order_items_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['public.sections.id'], name='order_items_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_items_pkey'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items', schema='public')
    op.drop_table('sections', schema='public')
    op.drop_table('event_artists', schema='public')
    op.drop_table('orders', schema='public')
    op.drop_table('events', schema='public')
    op.drop_table('venues', schema='public')
    op.drop_table('customers', schema='public')
    op.drop_table('artists', schema='public')
    # ### end Alembic commands ###
